// === FLOOD MAP CONFIGURATION ===
const CONFIG = {
    center: [-66.45, 18.22],
    zoom: 9,
    maxZoom: 18,
    floodDataFile: 'data/puerto_rico_alto_riesgo_enriched.json',
    searchViewbox: '-67.95,18.52,-65.22,17.92'
};

// Continuous gradient stops mapped to RISK_SCORE (0–10)
// Generated by scripts/extract_flood_data.py; scores range 4.5–10 in this dataset
const GRADIENT_STOPS = [
    [4.5,  '#FEB24C'],
    [6.0,  '#FD8D3C'],
    [7.0,  '#FC4E2A'],
    [7.5,  '#E31A1C'],
    [9.0,  '#BD0026'],
    [10.0, '#67000D'],
];

// BFE gradient stops (feet); range in dataset: 0.9–14.3 ft
const BFE_GRADIENT_STOPS = [
    [0.9,  '#deebf7'],
    [3.0,  '#9ecae1'],
    [6.0,  '#4292c6'],
    [10.0, '#08519c'],
    [14.3, '#08306b'],
];
const BFE_NO_DATA_COLOR = '#d0d0d0';

// Flat fallback colors (used in popups)
const TIER_COLORS = {
    5: '#67000D',
    4: '#E31A1C',
    3: '#FD8D3C',
    2: '#FEB24C',
    1: '#cccccc',
};

let colorMode = 'risk'; // 'risk' | 'bfe'

// === MAP INITIALIZATION ===
let map;
let searchResultMarker = null;

function initMap() {
    map = new maplibregl.Map({
        container: 'map',
        style: {
            version: 8,
            sources: {
                'simple-tiles': {
                    type: 'raster',
                    tiles: ['https://basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png'],
                    tileSize: 256,
                    attribution: '&copy; OpenStreetMap &copy; CARTO'
                },
                'satellite-tiles': {
                    type: 'raster',
                    tiles: [
                        'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
                    ],
                    tileSize: 256,
                    attribution: 'Esri World Imagery'
                }
            },
            layers: [
                {
                    id: 'satellite-layer',
                    type: 'raster',
                    source: 'satellite-tiles',
                    paint: { 'raster-opacity': 0 }
                },
                {
                    id: 'simple-layer',
                    type: 'raster',
                    source: 'simple-tiles',
                    paint: { 'raster-opacity': 1 }
                }
            ]
        },
        center: CONFIG.center,
        zoom: CONFIG.zoom,
        maxZoom: CONFIG.maxZoom,
        pitch: 0,
        attributionControl: false
    });

    map.addControl(new maplibregl.AttributionControl({ compact: true }), 'top-right');

    map.on('load', () => {
        loadFloodData();
        setupPopups();
    });
}

// === PAINT EXPRESSIONS ===
function buildRiskExpr() {
    return [
        'interpolate', ['linear'], ['get', 'RISK_SCORE'],
        ...GRADIENT_STOPS.flatMap(([s, c]) => [s, c])
    ];
}

function buildBfeExpr() {
    return [
        'case',
        ['==', ['typeof', ['get', 'BFE_CLEAN']], 'number'],
        [
            'interpolate', ['linear'], ['get', 'BFE_CLEAN'],
            ...BFE_GRADIENT_STOPS.flatMap(([s, c]) => [s, c])
        ],
        BFE_NO_DATA_COLOR
    ];
}

// === FLOOD DATA ===
function loadFloodData() {
    map.addSource('flood-data', {
        type: 'geojson',
        data: CONFIG.floodDataFile
    });

    const gradientExpr = buildRiskExpr();

    map.addLayer({
        'id': 'flood-fill',
        'type': 'fill',
        'source': 'flood-data',
        'layout': {},
        'paint': {
            'fill-color': gradientExpr,
            'fill-opacity': 0.65
        }
    });

    map.addLayer({
        'id': 'flood-line',
        'type': 'line',
        'source': 'flood-data',
        'layout': {},
        'paint': {
            'line-color': '#000000',
            'line-width': 0.4,
            'line-opacity': 0.12
        }
    });

    // Special outline for floodway zones (most dangerous corridors)
    map.addLayer({
        'id': 'flood-floodway',
        'type': 'line',
        'source': 'flood-data',
        'filter': ['==', ['get', 'IS_FLOODWAY'], true],
        'layout': {},
        'paint': {
            'line-color': '#003580',
            'line-width': 2,
            'line-opacity': 0.85
        }
    });

    // Hide loader when map is idle
    const hideLoader = () => {
        const loader = document.getElementById('loader');
        if (loader && !loader.classList.contains('fade-out')) {
            loader.classList.add('fade-out');
            setTimeout(() => { loader.style.display = 'none'; }, 500);
        }
    };
    map.once('idle', hideLoader);
    setTimeout(hideLoader, 3000);
}

// === POPUPS ===
function setupPopups() {
    map.on('click', 'flood-fill', (e) => {
        const props = e.features[0].properties;
        const { riskLevel, color } = getRiskInfo(props);

        const score   = props.RISK_SCORE != null ? props.RISK_SCORE.toFixed(1) : '—';
        const tier    = props.HAZARD_TIER || '—';
        const depth   = props.DEPTH_CLEAN != null ? `${props.DEPTH_CLEAN} ft` : null;
        const bfe     = props.BFE_CLEAN   != null ? `${props.BFE_CLEAN} ft`   : null;
        const subtype = props.ZONE_SUBTY  || null;
        const floodway = props.IS_FLOODWAY;

        const description = `
            <span class="popup-zone" style="color: ${color}">Zone ${props.FLD_ZONE}</span>
            <div class="popup-desc">
                <strong>Risk:</strong> ${riskLevel}<br>
                <strong>Score:</strong> ${score} / 10 &nbsp;·&nbsp; Tier ${tier}<br>
                ${subtype  ? `<strong>Subtype:</strong> ${subtype}<br>` : ''}
                ${floodway ? `<strong style="color:#003580">⚠ Floodway</strong><br>` : ''}
                ${depth    ? `<strong>Flood Depth:</strong> ${depth}<br>` : ''}
                ${bfe      ? `<strong>Base Flood Elev.:</strong> ${bfe}` : ''}
            </div>
        `;

        new maplibregl.Popup().setLngLat(e.lngLat).setHTML(description).addTo(map);
    });

    map.on('mouseenter', 'flood-fill', () => map.getCanvas().style.cursor = 'pointer');
    map.on('mouseleave', 'flood-fill', () => map.getCanvas().style.cursor = '');
}

function getRiskInfo(props) {
    const zone    = (props.FLD_ZONE   || '').trim();
    const subtype = (props.ZONE_SUBTY || '').trim();
    const tier    = props.HAZARD_TIER || 3;

    const ZONE_LABELS = {
        VE:  'Coastal Storm High Hazard',
        AE:  '1% Annual Chance (Detailed)',
        AO:  '1% Annual Chance (Shallow Overflow)',
        AH:  '1% Annual Chance (Shallow Ponding)',
        A:   '1% Annual Chance (Approximate)',
        A99: '1% Annual Chance (Protected)',
        X:   subtype.includes('0.2 PCT') ? '0.2% Annual Chance (Moderate)' : 'Minimal Flood Hazard',
        D:   'Future Conditions (Undetermined)',
    };

    const riskLevel = ZONE_LABELS[zone] || 'Flood Hazard Area';
    const color     = TIER_COLORS[tier] || '#999';

    return { riskLevel, color };
}

// === SEARCH FUNCTIONALITY ===
function initSearch() {
    const searchInputEl = document.getElementById('search-input');
    const searchButton = document.getElementById('search-button');

    searchButton.addEventListener('click', performSearch);
    searchInputEl.addEventListener('keypress', (event) => {
        if (event.key === 'Enter') {
            performSearch();
        }
    });
}

async function performSearch() {
    const searchInputEl = document.getElementById('search-input');
    const searchStatus = document.getElementById('search-status');
    const query = searchInputEl.value.trim();

    if (!query) return;

    searchStatus.textContent = 'Searching...';
    const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query)}, Puerto Rico&format=json&limit=1&bounded=1&viewbox=${CONFIG.searchViewbox}`;

    try {
        const response = await fetch(url);
        if (!response.ok) throw new Error('Network error');
        const data = await response.json();

        if (data && data.length > 0) {
            const result = data[0];
            const lat = parseFloat(result.lat);
            const lon = parseFloat(result.lon);

            searchStatus.textContent = `Found: ${result.display_name.split(',')[0]}`;

            // Collapse panel on mobile after search
            const uiPanel = document.querySelector('.ui-panel');
            if (window.innerWidth <= 600) {
                uiPanel.classList.add('is-collapsed');
                searchInputEl.blur();
            }

            map.flyTo({
                center: [lon, lat],
                zoom: 15,
                essential: true
            });

            if (searchResultMarker) searchResultMarker.remove();

            const el = document.createElement('div');
            el.style.width = '24px';
            el.style.height = '24px';
            el.style.borderRadius = '50%';
            el.style.backgroundColor = '#ff3b30';
            el.style.border = '3px solid white';
            el.style.boxShadow = '0 4px 12px rgba(0,0,0,0.3)';

            searchResultMarker = new maplibregl.Marker({ element: el })
                .setLngLat([lon, lat])
                .addTo(map);

        } else {
            searchStatus.textContent = 'No results found.';
        }
    } catch (error) {
        searchStatus.textContent = 'Error searching.';
    }
}

// === COLOR MODE TOGGLE ===
function initColorToggle() {
    const btnRisk = document.getElementById('btn-color-risk');
    const btnBfe  = document.getElementById('btn-color-bfe');

    function setMode(mode) {
        colorMode = mode;
        const expr = mode === 'bfe' ? buildBfeExpr() : buildRiskExpr();
        if (map.getLayer('flood-fill')) {
            map.setPaintProperty('flood-fill', 'fill-color', expr);
        }
        btnRisk.classList.toggle('active', mode === 'risk');
        btnBfe.classList.toggle('active',  mode === 'bfe');

        document.getElementById('legend-risk').style.display = mode === 'risk' ? '' : 'none';
        document.getElementById('legend-bfe').style.display  = mode === 'bfe'  ? '' : 'none';
    }

    btnRisk.onclick = () => setMode('risk');
    btnBfe.onclick  = () => setMode('bfe');
}

// === UI CONTROLS ===
function initUI() {
    const uiPanel = document.querySelector('.ui-panel');
    const collapseBtn = document.getElementById('ui-collapse-btn');

    // Show panel expanded on desktop by default
    if (window.innerWidth > 600) {
        uiPanel.classList.remove('is-collapsed');
    }

    collapseBtn.addEventListener('click', () => {
        uiPanel.classList.toggle('is-collapsed');
    });

    // Map/Satellite toggle
    const btnSimple = document.getElementById('btn-simple');
    const btnSatellite = document.getElementById('btn-satellite');

    btnSimple.onclick = () => {
        btnSimple.classList.add('active');
        btnSatellite.classList.remove('active');
        map.setPaintProperty('simple-layer', 'raster-opacity', 1);
        map.setPaintProperty('satellite-layer', 'raster-opacity', 0);
        if (map.getLayer('flood-fill'))    map.setPaintProperty('flood-fill', 'fill-opacity', 0.65);
        if (map.getLayer('flood-floodway')) map.setPaintProperty('flood-floodway', 'line-opacity', 0.85);
    };

    btnSatellite.onclick = () => {
        btnSatellite.classList.add('active');
        btnSimple.classList.remove('active');
        map.setPaintProperty('simple-layer', 'raster-opacity', 0);
        map.setPaintProperty('satellite-layer', 'raster-opacity', 1);
        if (map.getLayer('flood-fill'))    map.setPaintProperty('flood-fill', 'fill-opacity', 0.4);
        if (map.getLayer('flood-floodway')) map.setPaintProperty('flood-floodway', 'line-opacity', 0.9);
    };
}

// === INITIALIZE EVERYTHING ===
document.addEventListener('DOMContentLoaded', () => {
    initMap();
    initSearch();
    initUI();
    initColorToggle();
});
